version: '3.8'

services:
  backend:
    image: node:18
    ports:
      - '4000:4000'
    volumes:
      - ./backend2:/backend2
      - npm-cache:/root/.npm
      - yarn-cache:/root/.yarn
    environment:
      YARN_CACHE_FOLDER: /root/.yarn
    working_dir: /backend2
    command: yarn start

  frontend:
    image: node:18
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
      - npm-cache:/root/.npm
      - yarn-cache:/root/.yarn
    environment:
      YARN_CACHE_FOLDER: /root/.yarn
    working_dir: /frontend
    command: yarn start

volumes:
  npm-cache:
  yarn-cache:
